### ISSUE TITLE
[setup-ghdl] "nightly" tag gone?

### ISSUE THREAD

**Issue by stnolting** [ghdl/ghdl#2973]
I am using the CI action to get GHDL:

```
- name: '📦 Install GHDL'
  uses: ghdl/setup-ghdl@v1
  with:
    version: nightly
    backend: mcode
```

However, this fails.

![Image](https://github.com/user-attachments/assets/fb9dc5a9-c525-4721-8cca-3adc4d8493e6)

I'm no expert, but it seems like the "nightly" tag is gone. Hardcoding the latest version works:

- name: '📦 Install GHDL'
  uses: ghdl/setup-ghdl@v1
  with:
    version: v5.0.1
    backend: mcode
```
